tap "1password/tap"
tap "dopplerhq/cli"
tap "grain-lang/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"
tap "jesseduffield/lazygit"
tap "oven-sh/bun"
tap "robotsandpencils/made"
tap "romkatv/powerlevel10k"
tap "sst/tap"
tap "xcodesorg/made"
brew "act"
brew "gmp"
brew "gcc"
brew "libyaml"
brew "openssl@3"
brew "readline"
brew "aider"
brew "aria2"
brew "bat"
brew "caddy"
brew "cmake"
brew "coreutils"
brew "curl"
brew "docker", link: false
brew "docker-compose"
brew "fd"
brew "gnutls"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "glab"
brew "gnu-sed"
brew "go"
brew "gzip"
brew "htop"
brew "icu4c@76"
brew "lazygit"
brew "lua-language-server"
brew "make"
brew "mas"
brew "neomutt"
brew "tree-sitter"
brew "neovim"
brew "neovim-remote"
brew "nmap"
brew "opam"
brew "openssl@1.1"
brew "openvpn"
brew "pandoc"
brew "pkgconf"
brew "powerlevel10k"
brew "pyenv"
brew "python@3.11"
brew "rbenv"
brew "ripgrep"
brew "rustup"
brew "shfmt"
brew "speedtest-cli"
brew "stow"
brew "tmux"
brew "translate-shell"
brew "tree"
brew "unzip"
brew "watchman"
brew "wget"
brew "zlib"
brew "zoxide"
brew "dopplerhq/cli/doppler"
brew "oven-sh/bun/bun"
brew "sst/tap/opencode"
brew "xcodesorg/made/xcodes"
cask "1password"
cask "1password-cli"
cask "affinity-designer"
cask "alfred"
cask "alt-tab"
cask "android-file-transfer"
cask "android-studio"
cask "arc"
cask "balenaetcher"
cask "basictex"
cask "discord"
cask "docker-desktop"
cask "dropbox"
cask "figma"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "grain"
cask "hammerspoon"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "kitty"
cask "krisp"
cask "logi-options+"
cask "michaelvillar-timer"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "monitorcontrol"
cask "neovide-app"
cask "ngrok"
cask "notion"
cask "obs"
cask "orion"
cask "postman"
cask "proxy-audio-device"
cask "sigmaos"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "tomatobar"
cask "tunnelblick"
cask "ukelele"
cask "visual-studio-code"
cask "vlc"
cask "zed"
cask "zed@preview"
cask "zen"
cask "zulu"
cask "zulu@17"
mas "1Password for Safari", id: 1569813296
mas "Adblock Plus", id: 1432731683
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "AusweisApp", id: 948660805
mas "Bear", id: 1091189122
mas "Brother iPrint&Scan", id: 1193539993
mas "Cleaner One", id: 1473079126
mas "ColorSlurp", id: 1287239339
mas "Dark Reader for Safari", id: 1438243180
mas "Flow", id: 1423210932
mas "GarageBand", id: 682658836
mas "Geeps", id: 6476961115
mas "GIPHY CAPTURE", id: 668208984
mas "HP", id: 1474276998
mas "iMovie", id: 408981434
mas "IP Scanner", id: 6443819966
mas "Keynote", id: 409183694
mas "Linearity Curve", id: 1219074514
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Toggl Track", id: 1291898086
mas "Trello", id: 1278508951
mas "Vimari", id: 1480933944
