tap "1password/tap"
tap "anomalyco/tap"
tap "facebook/fb"
tap "jesseduffield/lazygit"
tap "oven-sh/bun"
tap "romkatv/powerlevel10k"
tap "wix/brew"
tap "xcodesorg/made"
brew "act"
brew "openssl@3"
brew "aria2"
brew "bat"
brew "cmake"
brew "libyaml"
brew "cocoapods"
brew "gmp"
brew "coreutils"
brew "curl"
brew "docker"
brew "docker-compose"
brew "fastlane"
brew "fd"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "glab"
brew "gnu-sed"
brew "gnutls"
brew "go"
brew "gzip"
brew "htop"
brew "icu4c@76"
brew "lazygit"
brew "lua-language-server"
brew "make"
brew "mas"
brew "mistral-vibe"
brew "tree-sitter"
brew "neovim"
brew "nmap"
brew "opam"
brew "openvpn"
brew "pandoc"
brew "picocom"
brew "pipx"
brew "pkgconf"
brew "powerlevel10k"
brew "pyenv"
brew "python@3.11"
brew "rbenv"
brew "ripgrep"
brew "rustup"
brew "scrcpy"
brew "shfmt"
brew "speedtest-cli"
brew "stow"
brew "tmux"
brew "translate-shell"
brew "tree"
brew "typos-cli"
brew "unzip"
brew "uv"
brew "watchman"
brew "wget"
brew "wimlib"
brew "zlib"
brew "zoxide"
brew "anomalyco/tap/opencode"
brew "facebook/fb/idb-companion"
brew "oven-sh/bun/bun"
brew "wix/brew/applesimutils"
brew "xcodes"
cask "1password"
cask "1password-cli"
cask "affinity"
cask "alfred"
cask "alt-tab"
cask "android-studio"
cask "arc"
cask "balenaetcher"
cask "claude"
cask "claude-code"
cask "discord"
cask "docker-desktop"
cask "dropbox"
cask "expo-orbit"
cask "figma"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "karabiner-elements"
cask "krisp"
cask "logi-options+"
cask "michaelvillar-timer"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "monitorcontrol"
cask "neovide-app"
cask "ngrok"
cask "notion"
cask "obs"
cask "postman"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "tomatobar"
cask "tunnelblick"
cask "ukelele"
cask "visual-studio-code"
cask "zed"
cask "zed@preview"
cask "zen"
cask "zulu"
mas "1Password for Safari", id: 1569813296
mas "Adblock Plus", id: 1432731683
mas "Amphetamine", id: 937984704
mas "AusweisApp", id: 948660805
mas "Bear", id: 1091189122
mas "Brother iPrint&Scan", id: 1193539993
mas "Cleaner One", id: 1473079126
mas "ColorSlurp", id: 1287239339
mas "Dark Reader for Safari", id: 1438243180
mas "Flow", id: 1423210932
mas "GarageBand", id: 682658836
mas "HP", id: 1474276998
mas "iMovie", id: 408981434
mas "IP Scanner", id: 6443819966
mas "Keynote", id: 361285480
mas "Magnet", id: 441258766
mas "Numbers", id: 361304891
mas "Pages", id: 361309726
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Toggl Track", id: 1291898086
mas "Trello", id: 1278508951
mas "Vimari", id: 1480933944
mas "WhatsApp", id: 310633997
npm "@expo/ngrok"
npm "@vscode/vsce"
npm "alfred-dark-mode"
npm "alfred-npms"
npm "corepack"
npm "eas-cli"
npm "ios-deploy"
npm "quicktype"
npm "tsx"
