git:
  paging:
    colorArg: always
    pager: delta --features dark-mode --paging=never
gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - reverse 
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - yellow
