git:
  paging:
    colorArg: always
    pager: delta --features light-mode --paging=never
gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - reverse 
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - white
    cherryPickedCommitFgColor:
      - magenta
