return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	lazy = false,
	build = ":TSUpdate",
	cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
	keys = {
		{ "<C-S-P>", "<cmd>Inspect<cr>", mode = "n", desc = "Highlight Capture" },
	},
	opts = {
		ensure_installed = {
			"bash",
			"typescript",
			"typescriptreact",
			"tsx",
			"javascript",
			"javascriptreact",
			"java",
			"elixir",
			"json",
			"jsonc",
			"css",
			"lua",
			"make",
			"dockerfile",
			"gitattributes",
			"gitignore",
			"graphql",
			"groovy",
			"html",
			"jsdoc",
			"php",
			"python",
			"ruby",
			"regex",
			"scss",
			"toml",
			"yaml",
			"vim",
			"vimdoc",
			"swift",
			"svelte",
			"rust",
			"r",
			"go",
			"cpp",
			"sql",
			"kotlin",
			"dart",
			"scala",
			"haskell",
			"erlang",
			"markdown",
			"markdown_inline",
			"objc",
			"ini",
		},
	},
	config = function(plugin, opts)
		require("nvim-treesitter").setup()
		require("nvim-treesitter").install(opts.ensure_installed)

		vim.api.nvim_create_autocmd("FileType", {
			pattern = opts.ensure_installed,
			callback = function(args)
				vim.treesitter.start(args.buf)
			end,
		})
	end,
}
